# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='from_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.Question'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to='users.Profile'),
        ),
    ]
