# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20160422_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
